### PR TITLE
feat(sql): code refactor for misleading-indentation(#1542)

### LINKED ISSUE #1542: feature: rm useless code in sql_optimizer.cc
**Is your feature request related to a problem? Please describe.**

As we support delete & update now, the code next should be deleted.
Introduced on pr: https://github.com/stoneatom/stonedb/commit/ea99be984b8c883d507ec781ce46ba445799eb3b
```
    /*
      The primary key of the tianmu engine does not support delete and update statements.
      The following codes can be deleted after subsequent support
    */
    TABLE *const table= join_tab->table();
    bool tianmu_engine = table->s->db_type() ? table->s->db_type()->db_type == DB_TYPE_TIANMU: false;
    enum_sql_command sqlCommand = thd->lex->sql_command;
    bool tianmuDeleteOrUpdate = (tianmu_engine && (sqlCommand == SQLCOM_DELETE ||
                                          sqlCommand == SQLCOM_DELETE_MULTI ||
                                          sqlCommand == SQLCOM_UPDATE ||
                                          sqlCommand == SQLCOM_UPDATE_MULTI));

    if (!tianmuDeleteOrUpdate && update_ref_and_keys(thd, &keyuse_array, join_tab, tables, where_cond,
                            cond_equal, ~select_lex->outer_join, select_lex,
                            &sargables))
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by zzzz-vincent**
## Summary about this PR

Issue Number: close #1542

## Tests Check List

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [x] New Feature
- [ ] Bug Fix
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

### CODE REVIEW

**Comment by hustjieke** [comment]
These code  causes unpredictable behavior?

**Comment by hustjieke** [comment]
These changes may cause unexpected behaviour on `innodb`, can you make a regression test on `innodb`?

The cmd is:
```
./mysql-test-run.pl --suite=innodb,main --mysqld=--default-storage-engine=innodb --nowarnings --force --nocheck-testcases --retry=0 --do-test-list=./suite/innodb/include/innodb_testlist --parallel=15
```

Thanks!

**Comment by zzzz-vincent** [comment]
@hustjieke thanks for pointing out. Will take a look soon.

**Comment by konghaiya** [comment]
From the test results, it seems that some of the previous modifications have solved the problem of primary key scanning
It should be possible to relax the restrictions on the use of primary keys,

**Review by konghaiya — APPROVED** [review]
LGTM

**Review by RingsC — APPROVED** [review]
LGTM, thanks

**Pull request merged**
