### PR TITLE
feat(tianmu): fix up the compile warnings on CentOS. (#844)

### PR DESCRIPTION
**Pull request by lujiashun**
## Summary about this PR

Issue Number: ref  #844

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [X] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [X] New Feature
- [ ] Bug Fix
- [ ] Improvement
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

### CODE REVIEW

**Comment by lujiashun** [comment]
left two warnings， deal these later。
```
/__w/stonedb/stonedb/storage/tianmu/mm/tcm/span.cpp:50:9: warning: 'void* memset(void*, int, size_t)' offset [0, 31] is out of the bounds [0, 0] [-Warray-bounds]
/__w/stonedb/stonedb/storage/tianmu/system/channel.cpp:51:50: warning: '%02d' directive writing between 2 and 11 bytes into a region of size between 0 and 17 [-Wformat-overflow=]
```

**Review by RingsC — APPROVED** [review]
LGTM

**Review by DandreChen — APPROVED** [review]
LGTM.

**Review by hustjieke — APPROVED** [review]
LGTM

**Pull request merged**
