### PR TITLE
test(mtr):Add a test script select_group_by.test,select_order_by.test,temporary.test(#497)

### LINKED ISSUE #497: feature: Add the MTR test case for tianmu
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by shangyanwen**
## Summary about this PR

Issue Number: close #issue_number_you_created

## Tests Check List

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [ ] Bug Fix
- [ ] Improvement
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

### CODE REVIEW

**Comment by hustjieke** [comment]
Please do rebase to merge the commit logs into one commit.

**Review by isredstar — APPROVED** [review]
LGTM

**Review by hustjieke — APPROVED** [review]
LGTM

**Comment by hustjieke** [comment]
Please resolve conflict on this pr.

**Comment by shangyanwen** [comment]
One will be resubmitted

**Pull request closed without merging**
