### PR TITLE
fix: docs some minors in README

### LINKED ISSUE #1254: docs: typos in README
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Description

image

### Self-service

- [ ] I'd be willing to address this documentation request myself.

### PR DESCRIPTION
**Pull request by amber-moe**
## Summary about this PR

Issue Number: close #1254 

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [X] No code

## Changelog

- [ ] New Feature
- [ ] Bug Fix
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [X] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

### CODE REVIEW

**Comment by hustjieke** [comment]
Thanks for you pr @Amber1990Zhang 
PTAL @Nliver

**Comment by Nliver** [comment]
Thank you very much for correcting the documentation  @Amber1990Zhang.
Of course, I sincerely hope that you can work with us in the future to develop StoneDB Community Edition. You know, writing code is probably more fun than fixing punctuation, right? Come and join us, we are waiting for you ~

**Review by Nliver — APPROVED** [review]
LGTM

**Review by hustjieke — APPROVED** [review]
LGTM

**Pull request merged**
