### PR TITLE
fix(sql): fix crash when executing sql statement (#212)

### LINKED ISSUE #191: feature: Modify the wrong result of the test case in the "mysql-test/r"
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Modify the wrong result of the test case under "mysql-test/r"

### LINKED ISSUE #212: bug: stonedb crashes when executing "partition_deprecation.test" test case
### Describe the problem

stonedb crashes when executing "partition_deprecation.test test" case

### Expected behavior

_No response_

### How To Reproduce

```
./mtr partition_deprecation.test test

### Environment

centos7.5 
stonedb5.7

### Are you interested in submitting a PR to solve the problem?

- [X] Yes, I will!

### PR DESCRIPTION
**Pull request by lylth**
## Summary about this PR

Issue Number: close #212 
fix(sql): fix crash when executing sql statement (#212)
[summary]
1.In this test case scenario, the parameter of the strlen function is a null pointer , and the analysis code logically deletes the useless code.

## Tests Check List

- [ ] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [x] Bug Fix
- [x] Improvement
- [ ] Performance Improvement
- [x] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
Issue Number: close https://github.com/stoneatom/stonedb/issues/191
fix(mtr): fix the wrong result of the test case in the mysql-test/r. (https://github.com/stoneatom/stonedb/issues/191)
[summary]Issue Number: close https://github.com/stoneatom/stonedb/issues/191
fix(mtr): fix the wrong result of the test case in the mysql-test/r. (https://github.com/stoneatom/stonedb/issues/191)
[summary]

### CODE REVIEW

**Comment by lylth** [comment]
There is no problem with testing comment  functions
```
mysql> create table test( ID int not null default 0 comment '用户ID');
Query OK, 0 rows affected (0.01 sec)
mysql> show full columns from test;
+-------+---------+-----------+------+-----+---------+-------+---------------------------------+--------------------------------------+
| Field | Type    | Collation | Null | Key | Default | Extra | Privileges                      | Comment                              |
+-------+---------+-----------+------+-----+---------+-------+---------------------------------+--------------------------------------+
| ID    | int(11) | NULL      | NO   |     | 0       |       | select,insert,update,references | 用户ID; Size[MB]: 0.1; Ratio: 0.00   |
+-------+---------+-----------+------+-----+---------+-------+---------------------------------+--------------------------------------+
1 row in set (0.01 sec)


mysql> create table test1( ID int not null default 0 comment '用户ID') engine=stonedb;
Query OK, 0 rows affected (0.00 sec)

mysql> show full columns from test1;
+-------+---------+-----------+------+-----+---------+-------+---------------------------------+--------------------------------------+
| Field | Type    | Collation | Null | Key | Default | Extra | Privileges                      | Comment                              |
+-------+---------+-----------+------+-----+---------+-------+---------------------------------+--------------------------------------+
| ID    | int(11) | NULL      | NO   |     | 0       |       | select,insert,update,references | 用户ID; Size[MB]: 0.1; Ratio: 0.00   |
+-------+---------+-----------+------+-----+---------+-------+---------------------------------+--------------------------------------+
1 row in set (0.00 sec)

**Comment by lylth** [comment]
```
[root@localhost /stonedb57/install/mysql-test]$./mtr partition_deprecation
Logging: ./mtr  partition_deprecation
MySQL Version 5.7.36
Checking supported features...
 - SSL connections supported
 - binaries are debug compiled
Collecting tests...
Checking leftover processes...
Removing old var directory...
Creating var directory '/stonedb57/install/mysql-test/var'...
Installing system database...
Using parallel: 1

==============================================================================

TEST                                      RESULT   TIME (ms) or COMMENT
--------------------------------------------------------------------------

worker[1] Using MTR_BUILD_THREAD 300, with reserved ports 13000..13009
worker[1] mysql-test-run: WARNING: running this script as _root_ will cause some tests to be skipped
[ 50%] main.partition_deprecation               [ pass ]  25466
[100%] shutdown_report                          [ pass ]
--------------------------------------------------------------------------
The servers were restarted 0 times
Spent 25.466 of 44 seconds executing testcases

Completed: All 2 tests were successful.

**Review by isredstar — APPROVED** [review]
Good job，improve update comment module of source code with 5.7 kernel

**Review by hustjieke — APPROVED** [review]
LGTM

**Pull request merged**
