### PR TITLE
fix(tianmu): fix group_concat_max_len warning (#338)

### LINKED ISSUE #338: bug:warning ‘@@group_concat_max_len' is deprecated and will be removed in a future release.
### Describe the problem

```Warning	1287	'@@group_concat_max_len' is deprecated and will be removed in a future release.```

group_concat_max_len is not deprecated and removed ,this warning is error

### Expected behavior

no warning

### How To Reproduce

```
cd /stonedb57/install/mysql-test
./mtr --suite=main query_cache --force --max-test-fail=0 --retry=0
./mtr --suite=main func_gconcat --force --max-test-fail=0 --retry=0
./mtr --suite=main join_outer_bka_nixbnl --force --max-test-fail=0 --retry=0
./mtr --suite=main join_outer_bka --force --max-test-fail=0 --retry=0
```

### Environment

```
../bin/mysqld  Ver 5.7.36-StoneDB for Linux on x86_64 (build-)
build information as follow:
        Repository address: https://github.com/zsp108/stonedb.git:stonedb-5.7
        Branch name: stonedb-5.7
        Last commit ID: c845005
        Last commit time: Date:   Mon Aug 1 14:48:29 2022 +0800
        Build time: Date: Mon Aug  1 07:29:08 UTC 2022

```

```
Linux ub01 5.4.0-117-generic #132-Ubuntu SMP Thu Jun 2 00:39:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

### Are you interested in submitting a PR to solve the problem?

- [x] Yes, I will!

### PR DESCRIPTION
**Pull request by DandreChen**
## Summary about this PR

Issue Number: close #338 

## Tests Check List

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [x] Bug Fix
- [ ] Improvement
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

### CODE REVIEW

**Comment by hustjieke** [comment]
image
Add the issue that should closed.

**Comment by DandreChen** [comment]
> 
have fixed it

**Comment by hustjieke** [comment]
Which sql raiseed this error ？ You can add some comment  after issue #338 
@DandreChen

**Review by isredstar — APPROVED** [review]
LGTM

**Review by RingsC — APPROVED** [review]

**Comment by DandreChen** [comment]
> Which sql raiseed this error ？ You can add some comment after issue #338 @DandreChen

have Commented it

**Comment by hustjieke** [comment]
> Which sql raiseed this error ？ You can add some comment after issue #338 @DandreChen

Great! LGTM.

**Review by hustjieke — APPROVED** [review]

**Pull request merged**
