### PR TITLE
feat(stonedb8.0:load binlog): support mysql load binlog. (#530)

### LINKED ISSUE #530: feat(stonedb): support mysql load binlog.
**Is your feature request related to a problem? Please describe.**

mysql load sql is executed, the binary log shoud be written to the binary log  file. 

**Describe the solution you'd like**

the binlog format is the same with the noraml, it is better to use the wrapper function "write_execute_load_query_log_event".
the function is a private memeber of Sql_cmd_load_table, change the private to public, and use the function in tianmu's RCTable::binlog_load_query_log_event.

**Describe alternatives you've considered**

1." change function from  private to public"  enlarges the function's usage scope, use a friend class is a consideration,but sql level will introduces many tianmu's dependency.

**Additional context**

### PR DESCRIPTION
**Pull request by lujiashun**
* use Sql_cmd_load_table::write_execute_load_query_log_event function to write mysql log binlog.

## Summary about this PR

Issue Number: close #530

mysql load sql is executed, the binary log shoud be written to the binary log file.

the binlog format is the same with the noraml, it is better to use the wrapper function "write_execute_load_query_log_event".
the function is a private memeber of Sql_cmd_load_table, change the private to public, and use the function in tianmu's RCTable::binlog_load_query_log_event.

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [X] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [X] New Feature
- [ ] Bug Fix
- [ ] Improvement
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

### CODE REVIEW

**Comment by lujiashun** [comment]
mysql-load binlog file of stonedb5.7
```

/*!50530 SET @@SESSION.PSEUDO_SLAVE_MODE=1*/;
/*!50003 SET @OLD_COMPLETION_TYPE=@@COMPLETION_TYPE,COMPLETION_TYPE=0*/;
DELIMITER /*!*/;
# at 4
#220919  5:50:20 server id 1  end_log_pos 123 CRC32 0x748f5204  Start: binlog v 4, server v 5.7.36-StoneDB-debug-log created 220919  5:50:20
# Warning: this binlog is either in use or was not closed properly.
BINLOG '
HAMoYw8BAAAAdwAAAHsAAAABAAQANS43LjM2LVN0b25lREItZGVidWctbG9nAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAEzgNAAgAEgAEBAQEEgAAXwAEGggAAAAICAgCAAAACgoKKioAEjQA
AQRSj3Q=
'/*!*/;
# at 123
#220919  5:50:20 server id 1  end_log_pos 154 CRC32 0x63ac705c  Previous-GTIDs
# [empty]
# at 154
#220919  5:51:12 server id 1  end_log_pos 219 CRC32 0x9118254e  Anonymous_GTID  last_committed=0        sequence_number=1       rbr_only=no
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 219
#220919  5:51:12 server id 1  end_log_pos 298 CRC32 0xc9077f51  Query   thread_id=3     exec_time=0     error_code=0
SET TIMESTAMP=1663566672/*!*/;
SET @@session.pseudo_thread_id=3/*!*/;
SET @@session.foreign_key_checks=1, @@session.sql_auto_is_null=0, @@session.unique_checks=1, @@session.autocommit=1/*!*/;
SET @@session.sql_mode=1344274432/*!*/;
SET @@session.auto_increment_increment=1, @@session.auto_increment_offset=1/*!*/;
/*!\C utf8 *//*!*/;
SET @@session.character_set_client=33,@@session.collation_connection=33,@@session.collation_server=45/*!*/;
SET @@session.lc_time_names=0/*!*/;
SET @@session.collation_database=DEFAULT/*!*/;
BEGIN
/*!*/;
# at 298
#220919  5:51:12 server id 1  end_log_pos 364 CRC32 0xccde2c66
#Begin_load_query: file_id: 1  block_len: 39
# at 364
#220919  5:51:12 server id 1  end_log_pos 603 CRC32 0x822d5b0f  Execute_load_query      thread_id=3     exec_time=0     error_code=0
use `lujs`/*!*/;
SET TIMESTAMP=1663566672/*!*/;
LOAD DATA LOCAL INFILE '/tmp/SQL_LOAD_MB-1-1' INTO TABLE `tmp_loaddata` FIELDS TERMINATED BY ',' ENCLOSED BY '' ESCAPED BY '\\' LINES TERMINATED BY '\n' (`id`, `name`)
/*!*/;
# file_id: 1
# at 603
#220919  5:51:12 server id 1  end_log_pos 683 CRC32 0x12765bb2  Query   thread_id=3     exec_time=0     error_code=0
SET TIMESTAMP=1663566672/*!*/;
COMMIT
/*!*/;
SET @@SESSION.GTID_NEXT= 'AUTOMATIC' /* added by mysqlbinlog */ /*!*/;
DELIMITER ;
# End of log file
/*!50003 SET COMPLETION_TYPE=@OLD_COMPLETION_TYPE*/;
/*!50530 SET @@SESSION.PSEUDO_SLAVE_MODE=0*/;

```

**Comment by lujiashun** [comment]
mysql-load binlog file of stonedb8.0
```
# The proper term is pseudo_replica_mode, but we use this compatibility alias
# to make the statement usable on server versions 8.0.24 and older.
/*!50530 SET @@SESSION.PSEUDO_SLAVE_MODE=1*/;
/*!50003 SET @OLD_COMPLETION_TYPE=@@COMPLETION_TYPE,COMPLETION_TYPE=0*/;
DELIMITER /*!*/;
# at 4
#220919  5:42:39 server id 1  end_log_pos 126 CRC32 0x9291bab9  Start: binlog v 4, server v 8.0.30-debug created 220919  5:42:39
# Warning: this binlog is either in use or was not closed properly.
BINLOG '
TwEoYw8BAAAAegAAAH4AAAABAAQAOC4wLjMwLWRlYnVnAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAEwANAAgAAAAABAAEAAAAYgAEGggAAAAICAgCAAAACgoKKioAEjQA
CigAAbm6kZI=
'/*!*/;
# at 126
#220919  5:42:39 server id 1  end_log_pos 157 CRC32 0x5c68bc70  Previous-GTIDs
# [empty]
# at 157
#220919  5:42:43 server id 1  end_log_pos 236 CRC32 0x92491781  Anonymous_GTID  last_committed=0        sequence_number=1       rbr_only=no     original_committed_timestamp=1663566163344924   immediate_commit_timestamp=1663566163344924     transaction_length=537
# original_commit_timestamp=1663566163344924 (2022-09-19 05:42:43.344924 UTC)
# immediate_commit_timestamp=1663566163344924 (2022-09-19 05:42:43.344924 UTC)
/*!80001 SET @@session.original_commit_timestamp=1663566163344924*//*!*/;
/*!80014 SET @@session.original_server_version=80030*//*!*/;
/*!80014 SET @@session.immediate_server_version=80030*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 236
#220919  5:42:43 server id 1  end_log_pos 318 CRC32 0x90301ba6  Query   thread_id=8     exec_time=0     error_code=0
SET TIMESTAMP=1663566163/*!*/;
SET @@session.pseudo_thread_id=8/*!*/;
SET @@session.foreign_key_checks=1, @@session.sql_auto_is_null=0, @@session.unique_checks=1, @@session.autocommit=1/*!*/;
SET @@session.sql_mode=1075838976/*!*/;
SET @@session.auto_increment_increment=1, @@session.auto_increment_offset=1/*!*/;
/*!\C utf8mb4 *//*!*/;
SET @@session.character_set_client=45,@@session.collation_connection=45,@@session.collation_server=45/*!*/;
SET @@session.lc_time_names=0/*!*/;
SET @@session.collation_database=DEFAULT/*!*/;
/*!80011 SET @@session.default_collation_for_utf8mb4=255*//*!*/;
BEGIN
/*!*/;
# at 318
#220919  5:42:43 server id 1  end_log_pos 384 CRC32 0x3cb778ba
#Begin_load_query: file_id: 1  block_len: 39
# at 384
#220919  5:42:43 server id 1  end_log_pos 611 CRC32 0x9bb29636  Execute_load_query      thread_id=8     exec_time=0     error_code=0
use `lujs`/*!*/;
SET TIMESTAMP=1663566163/*!*/;
LOAD DATA LOCAL INFILE '/tmp/SQL_LOAD_MB-1-0' INTO TABLE `tmp_loaddata` FIELDS TERMINATED BY ',' ENCLOSED BY '' ESCAPED BY '\\' LINES TERMINATED BY '\n'
/*!*/;
# file_id: 1
# at 611
#220919  5:42:43 server id 1  end_log_pos 694 CRC32 0x46badb95  Query   thread_id=8     exec_time=0     error_code=0
SET TIMESTAMP=1663566163/*!*/;
COMMIT
/*!*/;
SET @@SESSION.GTID_NEXT= 'AUTOMATIC' /* added by mysqlbinlog */ /*!*/;
DELIMITER ;
# End of log file
/*!50003 SET COMPLETION_TYPE=@OLD_COMPLETION_TYPE*/;
/*!50530 SET @@SESSION.PSEUDO_SLAVE_MODE=0*/;
```

**Review by andyli029 — APPROVED** [review]
LGTM.

**Review by DandreChen — APPROVED** [review]
LGTM.

**Pull request merged**
