### PR TITLE
feat(stonedb): add docs issue templates(#235)

### LINKED ISSUE #235: feature: why not add a documention issue templates
**Is your feature request related to a problem? Please describe.**

It is recommended to add a template for documentation issues

### PR DESCRIPTION
**Pull request by Nliver**
## Summary about this PR

Add docs issue templates.
Issue Number: close #235

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [X] No code

## Changelog

- [ ] New Feature
- [ ] Bug Fix
- [ ] Improvement
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [X] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [X] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

### CODE REVIEW

**Comment by hustjieke** [comment]
Can you add more infos about expected result in #235 ? Then we'll know what the doc template will be like.

**Comment by Nliver** [comment]
> Can you add more infos about expected result in #235 ? Then we'll know what the doc template will be like.

Well，it would be like this：

image

Obviously, I made some changes~

**Comment by hustjieke** [comment]
image

Add default title `docs:` here.

**Review by RingsC — APPROVED** [review]
Dont use unicode, especially  icon, chars in future again.

**Review by hustjieke — APPROVED** [review]
LGTM

**Pull request merged**
