### PR TITLE
fix(scripts): update man pages from MySQL Server 5.7.36

### LINKED ISSUE #1323: bug:  Type 'help' or '\h' for help doesn't work
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

```shell
mysql> help select

Nothing found
Please try to run 'help contents' for a list of all accessible topics

mysql> \h select

Nothing found
Please try to run 'help contents' for a list of all accessible topics

```

### Expected behavior

```shell
mysql> help select
Name: 'SELECT'
Description:
Syntax:
SELECT
    [ALL | DISTINCT | DISTINCTROW ]
    [HIGH_PRIORITY]
    [STRAIGHT_JOIN]
    [SQL_SMALL_RESULT] [SQL_BIG_RESULT] [SQL_BUFFER_RESULT]
    [SQL_CACHE | SQL_NO_CACHE] [SQL_CALC_FOUND_ROWS]
    select_expr [, select_expr] ...
    [into_option]
    [FROM table_references
      [PARTITION partition_list]]

```

### How To Reproduce

_No response_

### Environment

```shell
root@ub01:/stonedb57/install/bin# ./mysqld --version
./mysqld  Ver 5.7.36-StoneDB-v1.0.2 for Linux on x86_64 (build-)
build information as follow:
        Repository address: https://github.com/stoneatom/stonedb.git:stonedb-5.7-dev
        Branch name: stonedb-5.7-dev
        Last commit ID: 0f4250589
        Last commit time: Date:   Tue Feb 21 06:09:37 2023 +0000
        Build time: Date: Wed Feb 22 17:50:51 CST 2023
```

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

### PR DESCRIPTION
**Pull request by El-even-11**
## Summary about this PR

Issue Number: close #1323 

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

## Changelog

- [ ] New Feature
- [x] Bug Fix
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

### CODE REVIEW

**Review by RingsC — APPROVED** [review]
Thanks, LGTM.

**Comment by RingsC** [comment]
By the way, Would you like to add some MTR for this PR.

**Comment by El-even-11** [comment]
> By the way, Would you like to add some MTR for this PR.

OK. Let me have a try.

**Comment by El-even-11** [comment]
I've wrote some tests like:
```
SELECT * FROM mysql.help_category;

help 'SELECT';
```

When I do 
```
./mtr --record xxx.test
````
, the result is empty. But these queries will return correct results on stonedb instance.

So I tried 
```
./mtr --extern host=127.0.0.1 --extern port=3306 --extern user=root --extern password='xxx' --record xxx.test
````
to bind the tests to local stonedb instance, the result is correct.

I'm not sure what is going on. It seems that when I simply use `./mtr`, the `fill_help_tables.sql` is not loaded.

**Comment by RingsC** [comment]
> I've wrote some tests like:
> 
> ```
> SELECT * FROM mysql.help_category;
> 
> help 'SELECT';
> ```
> 
> When I do
> 
> ```
> ./mtr --record xxx.test
> ```
> 
> , the result is empty. But these queries will return correct results on stonedb instance.
> 
> So I tried
> 
> ```
> ./mtr --extern host=127.0.0.1 --extern port=3306 --extern user=root --extern password='xxx' --record xxx.test
> ```
> 
> to bind the tests to local stonedb instance, the result is correct.
> 
> I'm not sure what is going on. It seems that when I simply use `./mtr`, the `fill_help_tables.sql` is not loaded.

Do generateed help messages go in `scripts/sql_commands_help_data.h`?  If yes, you can open this file to verify it has been generated correctly. If yes, you build up this version binary, and test it mannually. 

About MTR. goes to source code directory, then into `mysql-test`, then write your own test.  just like 
```
cd `/home/xxx/workshop/stonedb-ver-1.0/mysql-test/t`.
touch help_message.test
vim help_message.test
```

then `make install `, and goes into `install_dir/mysql-test` to run `./mtr help_message --record`.

**Comment by RingsC** [comment]
> I've wrote some tests like:
> 
> ```
> SELECT * FROM mysql.help_category;
> 
> help 'SELECT';
> ```
> 
> When I do
> 
> ```
> ./mtr --record xxx.test
> ```
> 
> , the result is empty. But these queries will return correct results on stonedb instance.
> 
> So I tried
> 
> ```
> ./mtr --extern host=127.0.0.1 --extern port=3306 --extern user=root --extern password='xxx' --record xxx.test
> ```
> 
> to bind the tests to local stonedb instance, the result is correct.
> 
> I'm not sure what is going on. It seems that when I simply use `./mtr`, the `fill_help_tables.sql` is not loaded.

Do generateed help messages go in `scripts/sql_commands_help_data.h`?  If yes, you can open this file to verify it has been generated correctly. If yes, you build up this version binary, and test it mannually. 

About MTR. goes to source code directory, then into `mysql-test`, then write your own test.  just like 
```
cd `/home/xxx/workshop/stonedb-ver-1.0/mysql-test/t`.
touch help_message.test
vim help_message.test
```

then `make install `, and goes into `install_dir/mysql-test` to run `./mtr help_message --record`.

**Comment by El-even-11** [comment]
> Do generateed help messages go in `scripts/sql_commands_help_data.h`?

Yes. Help message data is in `build/build_stonedb_xxx/scripts/sql_commands_help_data.h`.

> and test it mannually.

Mannual test succeeded.
```
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 21
Server version: 5.7.36-StoneDB-v1.0.2.b91119278 build-

Copyright (c) 2021, 2022 StoneAtom Group Holding Limited
Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> help 'select';
Name: 'SELECT'
Description:
Syntax:
SELECT
    [ALL | DISTINCT | DISTINCTROW ]
    [HIGH_PRIORITY]
    [STRAIGHT_JOIN]
    [SQL_SMALL_RESULT] [SQL_BIG_RESULT] [SQL_BUFFER_RESULT]
    [SQL_CACHE | SQL_NO_CACHE] [SQL_CALC_FOUND_ROWS]
    select_expr [, select_expr] ...
...
```

> About MTR...

`./mtr help_message --record` failed. 
```
# help_message.test
help 'SELECT';
```
The recorded result is empty.
```
# help_message.result
help 'SELECT';
name	is_it_category
```
------
`./mtr help_message --record --extern host=127.0.0.1 --extern port=3306` succeeded. (bind to running stonedb instance)
```
# help_message.result
help 'SELECT';
name	description	example
SELECT	Syntax:
SELECT
    [ALL | DISTINCT | DISTINCTROW ]
    [HIGH_PRIORITY]
    [STRAIGHT_JOIN]
    [SQL_SMALL_RESULT] [SQL_BIG_RESULT] [SQL_BUFFER_RESULT]
    [SQL_CACHE | SQL_NO_CACHE] [SQL_CALC_FOUND_ROWS]
    select_expr [, select_expr] ...
...
```

**Comment by RingsC** [comment]
> 

MTR will start a stonedb instance before a mtr is executed. And, from your description, it seems that is not the latest build with your patch. Makes sure your build is installed in your proper directory. Thanks.

**Comment by El-even-11** [comment]
CI also failed as on my local machine. I'll take a deeper look.

**Review by hustjieke — APPROVED** [review]
nice job!
LGTM

**Comment by El-even-11** [comment]
I found the reason why `fill_help_tables.sql` is not loaded for mtr.

https://github.com/stoneatom/stonedb/blob/4ff00ea40e12f6f66c8fe417a571899f157fe423/mysql-test/mysql-test-run.pl#L3590-L3642

This is former `mysql-test-run.pl`. It will load `fill_help_tables.sql` by

```perl
mtr_appendfile_to_file("$sql_dir/fill_help_tables.sql", 
   $bootstrap_sql_file); 
```

But in newest `mysql-test-run.pl`, `fill_help_tables.sql` is not loaded.

https://github.com/stoneatom/stonedb/blob/b91119278a22d3d8180ecc80d3bd18a98d0f8f52/mysql-test/mysql-test-run.pl#L4075-L4122

I tried to modify `mysql-test-run.pl` and manually load `fill_help_tables.sql` and it works.

IMO it is better not to add mtr for this PR, or we seem to have to modify `mysql-test-run.pl` for CI. And after all, help messages can be displayed correctly when connecting to stonedb instance.

**Comment by RingsC** [comment]
> 

Thanks for you contrs. As your said, does not add mtr for help message. now, you can re-commit, and we will merge your PR into code base.

**Comment by El-even-11** [comment]
Thanks for your review!

**Review by adofsauron — APPROVED** [review]

**Pull request merged**
