### PR TITLE
fix(tianmu): modify the minimum value of bigint

### LINKED ISSUE #1361: bug:  the range of bigint value problem
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

```shell
mysql> CREATE TABLE int8_tbl(q1 int8, q2 int8);
Query OK, 0 rows affected (0.01 sec)

mysql> INSERT INTO int8_tbl VALUES ('-9223372036854775805','-9223372036854775807');
ERROR 1264 (22003): Out of range[-9223372036854775807, 9223372036854775807] for column 'q2' value: -9223372036854775807

```

### Expected behavior

`The value range of bigint should be determined`

### How To Reproduce

```sql
CREATE TABLE int8_tbl(q1 int8, q2 int8);
INSERT INTO int8_tbl VALUES ('-9223372036854775805','-9223372036854775807');
```

### Environment

```shell
root@ub01:/stonedb57/install/bin# ./mysqld --version
./mysqld  Ver 5.7.36-StoneDB-v1.0.2 for Linux on x86_64 (build-)
build information as follow:
        Repository address: https://github.com/stoneatom/stonedb.git:stonedb-5.7-dev
        Branch name: stonedb-5.7-dev
        Last commit ID: d66a3ca70
        Last commit time: Date:   Wed Mar 8 10:28:54 2023 +0800
        Build time: Date: Wed Mar  8 11:35:35 CST 2023
```

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

### PR DESCRIPTION
**Pull request by El-even-11**
## Summary about this PR

Issue Number: close #1361

## Tests Check List

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [x] Bug Fix
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

### CODE REVIEW

**Review by hustjieke — APPROVED** [review]
Nice job!

**Comment by hustjieke** [comment]
mtr runs error, you forget to fix the errors in signed_boundary.result:
```
--- /stonedb57/install/mysql-test/suite/tianmu/r/signed_boundary.result	2023-03-08 05:35:44.000000000 +0300
+++ /stonedb57/install/mysql-test/var/9/log/signed_boundary.reject	2023-03-09 13:21:17.076249651 +0300
@@ -14,7 +14,7 @@
 CREATE TABLE int64_(c_max bigint, c_min bigint) engine = tianmu;
 INSERT INTO int64_ values(-9223372036854775806, 9223372036854775807);
 INSERT INTO int64_ values(-9223372036854775807, 9223372036854775807);
-ERROR 22003: Out of range[-9223372036854775807, 9223372036854775807] for column 'c_max' value: -9223372036854775807
+ERROR 22003: Out of range[-9223372036854775806, 9223372036854775807] for column 'c_max' value: -9223372036854775807
```

**Comment by El-even-11** [comment]
> mtr runs error, you forget to fix the errors in signed_boundary.result:
> 
> ```
> --- /stonedb57/install/mysql-test/suite/tianmu/r/signed_boundary.result	2023-03-08 05:35:44.000000000 +0300
> +++ /stonedb57/install/mysql-test/var/9/log/signed_boundary.reject	2023-03-09 13:21:17.076249651 +0300
> @@ -14,7 +14,7 @@
>  CREATE TABLE int64_(c_max bigint, c_min bigint) engine = tianmu;
>  INSERT INTO int64_ values(-9223372036854775806, 9223372036854775807);
>  INSERT INTO int64_ values(-9223372036854775807, 9223372036854775807);
> -ERROR 22003: Out of range[-9223372036854775807, 9223372036854775807] for column 'c_max' value: -9223372036854775807
> +ERROR 22003: Out of range[-9223372036854775806, 9223372036854775807] for column 'c_max' value: -9223372036854775807
> ```

Fixed. Thanks for your review!

**Review by RingsC — APPROVED** [review]

**Comment by Nliver** [comment]
Nice job~

**Pull request merged**
