### PR TITLE
feat(tianmu): update MTR test cases,different mtr use different database. (#497)

### PR DESCRIPTION
**Pull request by lujiashun**
## Summary about this PR

Issue Number: ref  #497

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [ ] Bug Fix
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

### CODE REVIEW

**Comment by lujiashun** [comment]
```
 function changefile()
 {
 db_name=$1
 file_name=$2
 sed -i '/have_tianmu.inc/d' $file_name
 sed -i '/use test/d'  $file_name
 sed -i '/USE test/d'  $file_name
 sed -i  "1i\-\-source include/have_tianmu.inc\n\n\-\-disable_warnings\nDROP DATABASE IF EXISTS ${db_name};\n\-\-enable_warnings\n\nCREATE DATABASE ${db_name};\n\nUSE ${db_name};\n"  $file_name
 sed -i  '$G' $file_name
 sed -i  "\$aDROP DATABASE ${db_name};" $file_name
 sed -i '/./,/^$/!d' $file_name
 }
changefile	add_column_test	add_column.test
changefile	alter_table_test	alter_table.test
changefile	alter_table_mix_use_test	alter_table_mix_use.test
changefile	casewhen_test	casewhen.test
changefile	concat_test	concat.test
changefile	create_drop_users_test	create_drop_users.test
changefile	create_index_test	create_index.test
changefile	delete_test	delete.test
changefile	delete_all_rows_test	delete_all_rows.test
changefile	drop_column_test	drop_column.test
changefile	flow_control_function_test	flow_control_function.test
changefile	func_math_test	func_math.test
changefile	group_concat_test	group_concat.test
changefile	group_concat2_test	group_concat2.test
changefile	issue1000_test	issue1000.test
changefile	issue1034_test	issue1034.test
changefile	issue1054_test	issue1054.test
changefile	issue1065_test	issue1065.test
changefile	issue1070_test	issue1070.test
changefile	issue1090_test	issue1090.test
changefile	issue222_test	issue222.test
changefile	issue226_test	issue226.test
changefile	issue228_test	issue228.test
changefile	issue270_test	issue270.test
changefile	issue271_test	issue271.test
changefile	issue281_test	issue281.test
changefile	issue282_test	issue282.test
changefile	issue301_test	issue301.test
changefile	issue342_test	issue342.test
changefile	issue362_test	issue362.test
changefile	issue364_test	issue364.test
changefile	issue405_test	issue405.test
changefile	issue415_test	issue415.test
changefile	issue417_test	issue417.test
changefile	issue429_test	issue429.test
changefile	issue430_test	issue430.test
changefile	issue431_test	issue431.test
changefile	issue441_test	issue441.test
changefile	issue464_test	issue464.test
changefile	issue467_test	issue467.test
changefile	issue468_test	issue468.test
changefile	issue469_test	issue469.test
changefile	issue475_test	issue475.test
changefile	issue487_test	issue487.test
changefile	issue496_test	issue496.test
changefile	issue502_test	issue502.test
changefile	issue515_test	issue515.test
changefile	issue538_test	issue538.test
changefile	issue581_test	issue581.test
changefile	issue656_test	issue656.test
changefile	issue663_test	issue663.test
changefile	issue669_test	issue669.test
changefile	issue682_test	issue682.test
changefile	issue703_test	issue703.test
changefile	issue736_test	issue736.test
changefile	issue767_test	issue767.test
changefile	issue781_test	issue781.test
changefile	issue819_test	issue819.test
changefile	issue829_test	issue829.test
changefile	issue845_test	issue845.test
changefile	issue852_test	issue852.test
changefile	issue887_test	issue887.test
changefile	issue889_test	issue889.test
changefile	issue906_test	issue906.test
changefile	issue938_test	issue938.test
changefile	issue947_test	issue947.test
changefile	issue956_test	issue956.test
changefile	issue959_test	issue959.test
changefile	issue964_test	issue964.test
changefile	issue971_test	issue971.test
changefile	issue975_test	issue975.test
changefile	issue985_test	issue985.test
changefile	issue995_test	issue995.test
changefile	issue998_test	issue998.test
changefile	issue_566_test	issue_566.test
changefile	issues_tx417_test	issues_tx417.test
changefile	lz4_test	lz4.test
changefile	orquery_test	orquery.test
changefile	orquery1_test	orquery1.test
changefile	replace_test	replace.test
changefile	select_from_test	select_from.test
changefile	temporary_test	temporary.test
changefile	truncate_test	truncate.test


```

**Comment by lujiashun** [comment]
```
./mtr --suite=tianmu --record add_column
./mtr --suite=tianmu --record alter_table
./mtr --suite=tianmu --record alter_table_mix_use
./mtr --suite=tianmu --record casewhen
./mtr --suite=tianmu --record concat
./mtr --suite=tianmu --record create_drop_users
./mtr --suite=tianmu --record create_index
./mtr --suite=tianmu --record delete
./mtr --suite=tianmu --record delete_all_rows
./mtr --suite=tianmu --record drop_column
./mtr --suite=tianmu --record flow_control_function
./mtr --suite=tianmu --record func_math
./mtr --suite=tianmu --record group_concat
./mtr --suite=tianmu --record group_concat2
./mtr --suite=tianmu --record issue1000
./mtr --suite=tianmu --record issue1034
./mtr --suite=tianmu --record issue1054
./mtr --suite=tianmu --record issue1065
./mtr --suite=tianmu --record issue1070
./mtr --suite=tianmu --record issue1090
./mtr --suite=tianmu --record issue222
./mtr --suite=tianmu --record issue226
./mtr --suite=tianmu --record issue228
./mtr --suite=tianmu --record issue270
./mtr --suite=tianmu --record issue271
./mtr --suite=tianmu --record issue281
./mtr --suite=tianmu --record issue282
./mtr --suite=tianmu --record issue301
./mtr --suite=tianmu --record issue342
./mtr --suite=tianmu --record issue362
./mtr --suite=tianmu --record issue364
./mtr --suite=tianmu --record issue405
./mtr --suite=tianmu --record issue415
./mtr --suite=tianmu --record issue417
./mtr --suite=tianmu --record issue429
./mtr --suite=tianmu --record issue430
./mtr --suite=tianmu --record issue431
./mtr --suite=tianmu --record issue441
./mtr --suite=tianmu --record issue464
./mtr --suite=tianmu --record issue467
./mtr --suite=tianmu --record issue468
./mtr --suite=tianmu --record issue469
./mtr --suite=tianmu --record issue475
./mtr --suite=tianmu --record issue487
./mtr --suite=tianmu --record issue496
./mtr --suite=tianmu --record issue502
./mtr --suite=tianmu --record issue515
./mtr --suite=tianmu --record issue538
./mtr --suite=tianmu --record issue581
./mtr --suite=tianmu --record issue656
./mtr --suite=tianmu --record issue663
./mtr --suite=tianmu --record issue669
./mtr --suite=tianmu --record issue682
./mtr --suite=tianmu --record issue703
./mtr --suite=tianmu --record issue736
./mtr --suite=tianmu --record issue767
./mtr --suite=tianmu --record issue781
./mtr --suite=tianmu --record issue819
./mtr --suite=tianmu --record issue829
./mtr --suite=tianmu --record issue845
./mtr --suite=tianmu --record issue852
./mtr --suite=tianmu --record issue887
./mtr --suite=tianmu --record issue889
./mtr --suite=tianmu --record issue906
./mtr --suite=tianmu --record issue938
./mtr --suite=tianmu --record issue947
./mtr --suite=tianmu --record issue956
./mtr --suite=tianmu --record issue959
./mtr --suite=tianmu --record issue964
./mtr --suite=tianmu --record issue971
./mtr --suite=tianmu --record issue975
./mtr --suite=tianmu --record issue985
./mtr --suite=tianmu --record issue995
./mtr --suite=tianmu --record issue998
./mtr --suite=tianmu --record issue_566
./mtr --suite=tianmu --record issues_tx417
./mtr --suite=tianmu --record lz4
./mtr --suite=tianmu --record orquery
./mtr --suite=tianmu --record orquery1
./mtr --suite=tianmu --record replace
./mtr --suite=tianmu --record select_from
./mtr --suite=tianmu --record temporary
./mtr --suite=tianmu --record truncate

```

**Comment by lujiashun** [comment]
5 mtr cases is related with master-slave, not to deal with it for this PR.
```
issue1054.test
issue1090.test
issue819.test
issue889.test
issue956.test
```

**Review by RingsC — APPROVED** [review]
LGTM

**Review by adofsauron — APPROVED** [review]

**Review by shangyanwen — APPROVED** [review]
LGTM

**Review by isredstar — APPROVED** [review]

**Pull request merged**
