### PR TITLE
fix: max-width navbar search style

### PR DESCRIPTION
**Pull request by Agility6**
## Summary about this PR

Issue Number: close #issue_number_you_created

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [ ] Bug Fix
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [x] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

### before
image

### after
image

### CODE REVIEW

**Review by RingsC — APPROVED** [review]
Thanks, LGTM

**Comment by Nliver** [comment]
@Agility6 Thank you for your contribution, if you have any better ideas for our official website, please join us to contribute. We are preparing to update and upgrade the official website recently, we see that you have a strong interest in front-end development, if you are interested, you can do this with us~

**Review by Nliver — APPROVED** [review]
LGTM

**Review by 2724635499 — APPROVED** [review]

**Comment by Agility6** [comment]
> @Agility6 Thank you for your contribution, if you have any better ideas for our official website, please join us to contribute. We are preparing to update and upgrade the official website recently, we see that you have a strong interest in front-end development, if you are interested, you can do this with us~

Yes, I'm very interested in front-end and also in projects, and I'm currently learning React, and I'd love to join and contribute. But I'm still in the learning phase, so I don't know if I'm up to the task, I'm willing to try😁

**Pull request merged**
