### PR TITLE
feat(tianmu): To improve tianmu code(#11)

### PR DESCRIPTION
**Pull request by RingsC**
## Summary about this PR

[summary]
1: Using `RoughSetValue` to replace `RSValue`.
2: USing `common::ColumnType` to replace `common::CT`.

Issue Number: close #11

## Tests Check List

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [ ] Bug Fix
- [ ] Improvement
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

### CODE REVIEW

**Comment by hustjieke** [comment]
Failed for format checks.

**Review by DandreChen — APPROVED** [review]
LGTM.

**Review by lujiashun — APPROVED** [review]
LGTM

**Review by hustjieke — APPROVED** [review]
LGTM

**Pull request merged**
