### PR TITLE
feat(mtr): Modify innodb_*/t(s-x) MTR test case(#170)

### LINKED ISSUE #170: feature:  Modify innodb_*/t(s-x) MTR test case
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

>Pass the MTR test case test of "innodb_*/t (s-x)" module

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by konghaiya**
## Summary about this PR

Issue Number: close #170

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [ ] Bug Fix
- [x] Improvement
- [ ] Performance Improvement
- [x] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

### CODE REVIEW

**Comment by RingsC** [comment]
Which issue do you want to solve in this PR.

**Comment by konghaiya** [comment]
*The main task of modifying MTR test cases and the subtask of this modification are created.*
>Main task: 

- #171 
>Subtask:

 - #170

**Review by isredstar — APPROVED** [review]

**Comment by hustjieke** [comment]
The commit title `feat(stonedb)` to `feat(mtr)` will be much better.

**Comment by hustjieke** [comment]
LGTM.

**Comment by hustjieke** [comment]
Try to make the pr in another pull request.

**Pull request closed without merging**
