### PR TITLE
feat: add delete/drop into tianmu log stat

### PR DESCRIPTION
**Pull request by duanjr**
## Summary about this PR

feat: add delete/truncate into log stat (#1398 )

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

 Manual test

sql code:
```
DROP DATABASE THU;

CREATE DATABASE THU;

USE THU;

CREATE TABLE student (
    id INT NOT NULL,
    uid INT,
    name VARCHAR(20)
);

ALTER TABLE student ADD INDEX (uid);

ALTER TABLE student ADD INDEX (id);

INSERT INTO student VALUES (228, NULL, 'wangzhidong');

INSERT INTO student VALUES (238, 5, 'qianhoude');

INSERT INTO student VALUES (292, 3, 'sunxun');

INSERT INTO student VALUES (300, 5, 'xuchenxi');

SELECT * FROM student WHERE student.id = 228;

SELECT * FROM student WHERE student.uid = 5;

delete from student where uid = 5;

SELECT * FROM student;

truncate table student;

SELECT * FROM student;
```
related output in `tianmu.log`:
```
[2023-05-08 16:59:38.564431] [873585] [INFO] [engine.cpp:1614] MSG: Command: select 0/0, update 0/0, insert 0/0, delete 0/0, truncate 0/0, load 0/0, queries 0/1
[2023-05-08 17:00:38.564740] [873585] [INFO] [engine.cpp:1614] MSG: Command: select 0/0, update 0/0, insert 0/0, delete 0/0, truncate 0/0, load 0/0, queries 3/4
[2023-05-08 17:01:38.565053] [873585] [INFO] [engine.cpp:1614] MSG: Command: select 3/3, update 0/0, insert 4/4, delete 0/0, truncate 0/0, load 0/0, queries 13/17
[2023-05-08 17:02:38.565352] [873585] [INFO] [engine.cpp:1614] MSG: Command: select 3/6, update 0/0, insert 0/4, delete 1/1, truncate 1/1, load 0/0, queries 6/23
[2023-05-08 17:03:38.565661] [873585] [INFO] [engine.cpp:1614] MSG: Command: select 0/6, update 0/0, insert 0/4, delete 0/1, truncate 0/1, load 0/0, queries 0/23
```

## Changelog

- [x] New Feature
- [ ] Bug Fix
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

### CODE REVIEW

**Comment by konghaiya** [comment]
@duanjr  Why is it only open for delete and truncate, while others can also be opened?

**Comment by duanjr** [comment]
> @duanjr Why is it only open for delete and truncate, while others can also be opened?

I’m also confused about this, according to discussion [here](https://github.com/stoneatom/stonedb/issues/1398#issue-1626856819), we add log about delete and truncate because tianmu engine has just been able to support the corresponding operations. But before the tianmu engine supports delete, truncate and drop, we can output logs for operations such as creating tables. I don't know why the original developer didn't open them, so I didn't modify them without authorization.

**Comment by konghaiya** [comment]
Other operations are also supported by Tianmu and can be opened for testing

**Comment by konghaiya** [comment]
Previously, it was not supported because the Tianmu engine only serves as an AP engine and does not support some functions of these DDL and DML operations,
But now Tianmu has become an HTAP engine that supports these operations.

**Comment by duanjr** [comment]
Log for all operations are opened know, and the log info is like the first code line [here](https://github.com/stoneatom/stonedb/issues/1398#issuecomment-1537944859).
I'm not sure if further testing is needed.

**Comment by konghaiya** [comment]
> Log for all operations are opened know, and the log info is like the first code line [here](https://github.com/stoneatom/stonedb/issues/1398#issuecomment-1537944859). I'm not sure if further testing is needed.

You can send the test results here

**Review by konghaiya — APPROVED** [review]
LGTM

**Review by RingsC — APPROVED** [review]

**Pull request merged**
