### PR TITLE
feat(tianmu): mv func from public to protected(#1501)

### LINKED ISSUE #1501: feature: mv function from public to protected
**Is your feature request related to a problem? Please describe.**

`CompressedBitMap()` is a wrapper func used both by pack_str & pack_int, it is not a public interface, so we should mv it to protectded.

```
Class Pack {
public:
  // Compress bitmap
  bool CompressedBitMap(mm::MMGuard<uchar> &comp_buf, uint &comp_buf_size, std::unique_ptr<uint32_t[]> &ptr_buf,
                        uint32_t &dpn_num1);

protected:
...
...
```

**Describe the solution you'd like**

```
Class Pack {
protected:
  // Compress bitmap
  bool CompressedBitMap(mm::MMGuard<uchar> &comp_buf, uint &comp_buf_size, std::unique_ptr<uint32_t[]> &ptr_buf,
                        uint32_t &dpn_num1);
...
...
```

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by zzzz-vincent**
## Summary about this PR

Issue Number: close #1501

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [X] New Feature
- [ ] Bug Fix
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [X] Contains syntax changes
- [X] Contains variable changes
- [ ] Contains experimental features

### CODE REVIEW

**Comment by Nliver** [comment]
You are welcome to contribute to StoneDB. Please sign the CLA file. Note that your git configuration email must be the same as your Github account binding email.

**Comment by zzzz-vincent** [comment]
> You are welcome to contribute to StoneDB. Please sign the CLA file. Note that your git configuration email must be the same as your Github account binding email.

Added and re push. But it seems that this check is based on previous commits. And I am not sure if it is still possible to change that.

**Comment by hustjieke** [comment]
> > You are welcome to contribute to StoneDB. Please sign the CLA file. Note that your git configuration email must be the same as your Github account binding email.
> 
> Added and re push. But it seems that this check is based on previous commits. And I am not sure if it is still possible to change that.

After signed CLA, wait for a while，there will be some delay.

**Comment by Nliver** [comment]
> > You are welcome to contribute to StoneDB. Please sign the CLA file. Note that your git configuration email must be the same as your Github account binding email.
> 
> Added and re push. But it seems that this check is based on previous commits. And I am not sure if it is still possible to change that.

If it doesn't work for a long time, I actually recommend shutting down the PR and resubmitting it

**Comment by Nliver** [comment]
Well, it looks like your CLA process is stuck. I suggest you close this PR. @zzzz-vincent 

Then do the following:

1. Check all of your local Git commit email addresses;
2. Confirm whether this email address is the same as your Github binding email address;
3. If they are inconsistent, it is recommended that you modify them to be consistent.

**Pull request closed without merging**
