### PR TITLE
feat(index): refactor some code on index on issue1408

### LINKED ISSUE #1408: backport: porting some refactor code on tianmu engine
**Is your feature request related to a problem? Please describe.**

previous working issue: #407
commit id on stonedb-5.7-dev: b1a714127eddbb03dca549371a4e6c2feaf71e3d

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by hustjieke**
## Summary about this PR

Issue Number: close #1408

## Tests Check List

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [ ] Bug Fix
- [x] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

### CODE REVIEW

**Review by RingsC — APPROVED** [review]
LGTM

**Review by konghaiya — COMMENTED** [review]
When synchronizing 5.7 code in 8.0, should we also add the corresponding mtr?

**Comment by hustjieke** [comment]
> When synchronizing 5.7 code in 8.0, should we also add the corresponding mtr?

Not need here, we just port the changes in 5.7, we did not make bug fix or add features here, just refactor some code.

**Review by konghaiya — APPROVED** [review]
LGTM

**Pull request merged**
