### PR TITLE
fix(tianmu): revert some compress code issue. (#11)

### PR DESCRIPTION
**Pull request by lujiashun**
## Summary about this PR

Issue Number: ref #11

Related PR: https://github.com/stoneatom/stonedb/pull/832

## Tests Check List

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [X] Bug Fix
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

### CODE REVIEW

**Comment by hustjieke** [comment]
This is a revert pr, link the related pull request number you revert to and make a check again.

**Review by RingsC — APPROVED** [review]

**Comment by DandreChen** [comment]
LGTM

**Review by DandreChen — APPROVED** [review]
LGTM

**Review by isredstar — APPROVED** [review]
LGTM

**Pull request merged**
