### PR TITLE
fix(tianmu) There will be a problem of too many tuples when querying multiple tables (#554)

### LINKED ISSUE #554: bug: There will be a problem of too many tuples when querying multiple tables
### Describe the problem
```
 SELECT
    contract.id,
    sum( item_quantity ) AS total_nums,
    sum( detail_price ) AS total_prices 
    FROM
    contract
    JOIN contract_detail ON contract.id = contract_detail.contract_id
    JOIN day_dimension ON contract_detail.sign_day = day_dimension.day_str 
    GROUP BY
    contract.id;
```

```
[2022-09-21 16:03:12.342030] [10533] [INFO] [multi_index.cpp:198] MSG: MultiIndex::AddDimension_cross size: 1000 no_tuples: 0
[2022-09-21 16:03:12.342201] [10533] [INFO] [multi_index.cpp:198] MSG: MultiIndex::AddDimension_cross size: 1000 no_tuples: 1000
[2022-09-21 16:03:12.342304] [10533] [INFO] [multi_index.cpp:198] MSG: MultiIndex::AddDimension_cross size: 1000 no_tuples: 1000000
[2022-09-21 16:03:12.342359] [10533] [INFO] [multi_index.cpp:198] MSG: MultiIndex::AddDimension_cross size: 1000 no_tuples: 1000000000
[2022-09-21 16:03:12.342555] [10533] [INFO] [multi_index.cpp:198] MSG: MultiIndex::AddDimension_cross size: 243 no_tuples: 1000000000000
[2022-09-21 16:03:12.342626] [10533] [INFO] [multi_index.cpp:198] MSG: MultiIndex::AddDimension_cross size: 697 no_tuples: 243000000000000
[2022-09-21 16:03:12.342697] [10533] [INFO] [multi_index.cpp:198] MSG: MultiIndex::AddDimension_cross size: 1000 no_tuples: 169371000000000000
[2022-09-21 16:03:12.403332] [10533] [WARN] [exception.cpp:41] MSG: Exception: Too many tuples.    (48).
 
STACK TRACE BEGIN
        /stonedb57/install/bin/mysqld(Tianmu::common::OutOfMemoryException::OutOfMemoryException(std::string const&)+0x23) [0x29e4a4b]
        /stonedb57/install/bin/mysqld(Tianmu::core::Filter::Filter(long, unsigned int, bool, bool)+0x188) [0x29e51ec]
        /stonedb57/install/bin/mysqld(Tianmu::core::MIUpdatingIterator::MIUpdatingIterator(Tianmu::core::MultiIndex*, Tianmu::core::DimensionVector&)+0x187) [0x2d15439]
        /stonedb57/install/bin/mysqld(Tianmu::core::ParameterizedFilter::FilterDeletedByTable(Tianmu::core::JustATable*, int)+0xe5) [0x2d3c743]
        /stonedb57/install/bin/mysqld(Tianmu::core::ParameterizedFilter::UpdateMultiIndex(bool, long)+0x28f) [0x2d39c09]
        /stonedb57/install/bin/mysqld(Tianmu::core::Query::Preexecute(Tianmu::core::CompiledQuery&, Tianmu::core::ResultSender*, bool)+0x1bc3) [0x2a05157]
        /stonedb57/install/bin/mysqld(Tianmu::core::Engine::Execute(THD*, LEX*, Query_result*, st_select_lex_unit*)+0x5e1) [0x29d7153]
        /stonedb57/install/bin/mysqld(Tianmu::core::Engine::HandleSelect(THD*, LEX*, Query_result*&, unsigned long, int&, int&, int&, int)+0x8d8) [0x29d634c]
        /stonedb57/install/bin/mysqld(Tianmu::dbhandler::TIANMU_HandleSelect(THD*, LEX*, Query_result*&, unsigned long, int&, int&, int&, int)+0x5b) [0x2abb93d]
        /stonedb57/install/bin/mysqld() [0x22ffe85]
        /stonedb57/install/bin/mysqld(mysql_execute_command(THD*, bool)+0x9de) [0x22f9cad]
        /stonedb57/install/bin/mysqld(mysql_parse(THD*, Parser_state*)+0x557) [0x2300b8c]
        /stonedb57/install/bin/mysqld(dispatch_command(THD*, COM_DATA const*, enum_server_command)+0xadc) [0x22f6fd6]
        /stonedb57/install/bin/mysqld(do_command(THD*)+0x23c) [0x22f6179]
        /stonedb57/install/bin/mysqld(handle_connection+0x1ee) [0x23fa0bb]
        /stonedb57/install/bin/mysqld(pfs_spawn_thread+0x173) [0x2915cf1]
        /lib64/libpthread.so.0(+0x7ea5) [0x7f2d5d1b8ea5]
        /lib64/libc.so.6(clone+0x6d) [0x7f2d5a701b0d]
STACK TRACE END
```

### Expected behavior

_No response_

### How To Reproduce

_No response_

### Environment

_No response_

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

### PR DESCRIPTION
**Pull request by konghaiya**
- #554

## Summary about this PR

Issue Number: close #554

## Tests Check List

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

## Changelog

- [ ] New Feature
- [x] Bug Fix
- [ ] Improvement
- [ ] Performance Improvement
- [ ] Build/Testing/CI/CD
- [ ] Documentation
- [ ] Not for changelog (changelog entry is not required)

## Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

### CODE REVIEW

**Comment by konghaiya** [comment]
```
mysql> 
mysql> 
mysql>  SELECT
    ->     contract.id,
    ->     sum( item_quantity ) AS total_nums,
    ->     sum( detail_price ) AS total_prices 
    ->     FROM
    ->     contract
    ->     JOIN contract_detail ON contract.id = contract_detail.contract_id
    ->     JOIN day_dimension ON contract_detail.sign_day = day_dimension.day_str 
    ->     GROUP BY
    ->     contract.id;
Empty set (4.51 sec)

```

Normal query after repair

**Comment by adofsauron** [comment]
1. Is there a way to unit test this logic independently?
2. What is the specific data that will affect the performance of the query when the deleted data is filtered out?
3. The previous test only tested the query and deletion of a single table, but did not test the stability and performance of the function when multiple tables were associated with a large range of data. How can this submission strengthen the test of logic at the test case level

**Comment by konghaiya** [comment]
Yes, now we really lack independent and comprehensive testing methods for each unit. The unit test module is also under construction, and the performance test will be arranged later.

With the filtering logic added by the current delete function, if the queried table has no corresponding conditions and has deleted data, this will indeed have some impact on the query performance, because the corresponding PACK will be decompressed and scanned. This is a disadvantage of tag deletion.

**Comment by RingsC** [comment]
> 

I think that, here, text is better than pic

**Review by RingsC — APPROVED** [review]
LGTM

**Review by adofsauron — APPROVED** [review]
Merge first for customers

**Pull request merged**
